users:
  Andrew:
    username: Andrew
    articleIds:
      - 1
      - 2
    commentIds:
      - 1
articles:
  '1':
    id: 1
    title: Test
    url: Test
    username: Andrew
    commentIds: []
    upvotedBy: []
    downvotedBy: []
    comments: []
  '2':
    id: 2
    title: This new one
    url: test
    username: Andrew
    commentIds:
      - 1
    upvotedBy: []
    downvotedBy: []
    comments:
      - &ref_0
        id: 1
        body: test
        username: Andrew
        articleId: 2
        upvotedBy: []
        downvotedBy: []
comments:
  '1': *ref_0
nextArticleId: 3
nextCommentId: 2
